### ISSUE TITLE
The minimal thing to do when you write a script is to do a demo online

### ISSUE THREAD

**Issue by onigetoc** [Rich-Harris/roadtrip#13]
The minimal thing to do when you write a script like this is to do a demo online.
If you want user to try it.

**Comment by paulocoghi** [comment]
This an open-source voluntary project. It works very well but, in the moment, there are only the online documentation (which is more than enough considering that it is being delivered for free).

If you want something more documented, go with https://github.com/riot/route

It has a website and (as roadtrip) it has examples codes.
http://riotjs.com/api/route/

---

PS: A friendly attitude is always welcome!

**Comment by Rich-Harris** [comment]
Thanks @paulocoghi 👍 

@onigetoc I'm guessing English isn't your first language. Be that as it may, you may want to consider your tone when raising issues.
