### ISSUE TITLE
Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by cmalven** [Rich-Harris/roadtrip#25]
I've built a few sites using roadtrip, and there's an infrequent bug I've been noticing when navigating between routes:

`Uncaught TypeError: Cannot read property 'x' of undefined`

Here's the roadtrip code related to the error (though I imagine you can guess what it is):

```js
_target = {
  href: location$1.href,
  scrollX: scroll.x, // <--- the source of the error
  scrollY: scroll.y,
  popstate: true, // so we know not to manipulate the history
  fulfil: noop,
  reject: noop
};
```

## Steps to reproduce

- Open a page powered by roadtrip
- Navigate to any route
- Click the browser back button in the browser UI to return to the previous route
- Refresh the page using the browser UI
- Press the forward button in the browser UI to return to the previous route

I believe what is likely happening here is that refreshing the page clears road trip's `scrollHistory`, but roadtrip doesn't have a fallback for when a matching entry in the scroll history doesn't exist. Maybe?

**Comment by Kiho** [comment]
Hi @mrkishi,
Can you merge my PR and bump-up version in NPM?
